spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    click:
      driverClassName: ru.yandex.clickhouse.ClickHouseDriver
      url: jdbc:clickhouse://39.103.203.169:8123/default
      initialSize: 10
      maxActive: 100
      minIdle: 10
      maxWait: 6000